[pytest]
addopts = -v -s --alluredir=report --clean-alluredir
testpaths = ./script
python_files = test_*.py
python_classes = Test*
python_functions = test_*
#allure serve report启动在线报告单个
#pytest  allure serve report输入这两个命令可以全部启动生成。这两个是分开的哦